FROM jenkinsci/blueocean


USER root

RUN curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

RUN echo 'hello ??????'

RUN docker -v
